System: N64
Controllers:
  - Name: SonyPS4Dualshock4
    Mappings:
      - System: AnalogLeft
        Controller: RightAnalogLeft
      - System: AnalogUp
        Controller: RightAnalogUp
      - System: ButtonA
        Controller: ButtonCross
      - System: ButtonB
        Controller: ButtonSquare
      - System: ButtonCLeft
        Controller: LeftAnalogLeft
      - System: ButtonCUp
        Controller: LeftAnalogUp
      - System: ButtonDPadUp
        Controller: DPadUp
      - System: ButtonL
        Controller: ButtonL1
      - System: ButtonR
        Controller: ButtonR1
      - System: ButtonStart
        Controller: ButtonOptions
      - System: ButtonZ
        Controller: ButtonR2
  - Name: SonyPS5DualSense
    Mappings:
      - System: AnalogLeft
        Controller: RightAnalogLeft
      - System: AnalogUp
        Controller: RightAnalogUp
      - System: ButtonA
        Controller: ButtonCross
      - System: ButtonB
        Controller: ButtonSquare
      - System: ButtonCLeft
        Controller: LeftAnalogLeft
      - System: ButtonCUp
        Controller: LeftAnalogUp
      - System: ButtonDPadUp
        Controller: DPadUp
      - System: ButtonL
        Controller: ButtonL1
      - System: ButtonR
        Controller: ButtonR1
      - System: ButtonStart
        Controller: ButtonOptions
      - System: ButtonZ
        Controller: ButtonR2Button
